name             'mealplan'
maintainer       'Nathaniel Eliot'
maintainer_email 'temujin9@infochimps.com'
license          'Apache 2.0'
description      'Installs/Configures mealplan'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          IO.read(File.join(File.dirname(__FILE__), 'VERSION'))

depends         "ant"
depends         "apt"
depends         "boost"
depends         "build-essential"
depends         "emacs"
depends         "git"
depends         "hadoop_cluster"
depends         "java"
depends         "jruby"
depends         "minidash"
depends         "motd"
depends         "nfs"
depends         "nodejs"
depends         "ntp"
depends         "ntp"
depends         "openssl"
depends         "package_set"
depends         "pig"
depends         "route53"
depends         "runit"
depends         "thrift"
depends         "tuning"
depends         "users"
depends         "volumes"
depends         "xfs"
depends         "xml"
depends         "zlib"
depends         "zsh"

# depends         " "
# depends         " "
# depends         " "
# depends         " "
# depends         " "
# depends         " "
# depends         " "
# depends         " "
# depends         " "
# depends         " "
# depends         " "
# depends         " "
# depends         " "
# depends         " "
# depends         " "
# depends         " "
# depends         " "
# depends         " "
# depends         " "
# depends         " "
# depends         " "
# depends         " "
# depends         " "
# depends         " "
# depends         " "
